### ISSUE TITLE
Creating a sprint in the past shows up as upcoming

### ISSUE THREAD

**Issue by jorisslob** [steffchep/yanap#1]
Reproduction:

1) Create a sprint with start and end date in the past. I used Jun 5, 2016 and Jun 26, 2016.
2) The Sprint List now shows the sprint with the dates correctly, but the status shows up as "upcoming".

Expected behavior:

I would expect the status to be "ended"

**Comment by steffchep** [comment]
Hi Joris,

would you even expect to be able to create a sprint in the past? I'm debating whether to just forbid that - the whole point of the webapp is to ~plan~, after all :)

**Comment by jorisslob** [comment]
Sounds reasonable, until we have time travel, you can probably forbid that.
